# codemagic.yml

workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1 # استخدام جهاز ماك M1 السريع

    environment:
      flutter: 3.19.6
      java: 17
      groups:
        - codemagic-signing # اسم مجموعة متغيرات التوقيع

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
