# codemagic.yml - نسخة معدلة لبناء APK من نوع DEBUG

workflows:
  android-build-debug: # تم تغيير الاسم ليكون أوضح
    name: Android Debug Build
    instance_type: mac_mini_m1

    environment:
      flutter: 3.19.6
      java: 17
      # تم حذف مجموعة التوقيع "groups" لأننا لا نحتاجها في نسخة الـ debug

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK (Debug)
        script: |
          flutter build apk --debug # <-- التغيير الأهم: من release إلى debug

    artifacts:
      # المسار يتغير أيضاً ليعكس نوع النسخة
      - build/app/outputs/flutter-apk/app-debug.apk
