name: age_calculator_smart
description: A new Flutter project for a smart age calculator.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # لدعم اللغة العربية
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0 # لإضافة خطوط جميلة
  intl: ^0.20.1 # لتنسيق الأرقام والتواريخ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true # ضروري لدعم اللغة العربية
